-- Limit profile table: per-channel (ATM, POS, E-commerce) daily/monthly/yearly amounts (Oracle 19c)
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE LIMIT_PROFILE (
    PROFILE_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
    PROFILE_NAME VARCHAR2(255),
    CURRENCY_CODE VARCHAR2(10),
    ATM_DAILY_AMOUNT NUMBER(18,2),
    ATM_MONTHLY_AMOUNT NUMBER(18,2),
    ATM_YEARLY_AMOUNT NUMBER(18,2),
    POS_DAILY_AMOUNT NUMBER(18,2),
    POS_MONTHLY_AMOUNT NUMBER(18,2),
    POS_YEARLY_AMOUNT NUMBER(18,2),
    ECOMMERCE_DAILY_AMOUNT NUMBER(18,2),
    ECOMMERCE_MONTHLY_AMOUNT NUMBER(18,2),
    ECOMMERCE_YEARLY_AMOUNT NUMBER(18,2),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR2(50)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMIT;
