-- PCI DSS: Add CARD_ID to CARD_ACCOUNT for lookup without storing PAN. PAN retained until app uses CARD_ID.
ALTER TABLE CARD_ACCOUNT ADD CARD_ID NUMBER(19);

UPDATE CARD_ACCOUNT
SET CARD_ID = (SELECT CARD_ID FROM CARD c WHERE c.PAN = CARD_ACCOUNT.PAN)
WHERE PAN IS NOT NULL;

ALTER TABLE CARD_ACCOUNT ADD CONSTRAINT FK_CARD_ACCT_CARD_ID FOREIGN KEY (CARD_ID) REFERENCES CARD(CARD_ID);

COMMIT;
