-- V15: Add surrogate primary key (ID) and Oracle sequence to tables that lack one;
-- establish foreign keys by ID where applicable.
-- Order: 1) Create sequences 2) Add ID + backfill on reference tables 3) Add _ID columns on children + backfill + FKs 4) Drop old FKs 5) Drop old PKs, add new PKs and UNIQUE on former keys.

-- ========== 1. CREATE SEQUENCES ==========
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE ACCOUNT_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE ACCOUNT_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE RESPONSE_CODE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE USM_PERMISSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE USM_USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE USM_GROUP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE BRANCH_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE CARD_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE CARD_PRODUCT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE CARD_PRODUCTION_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE CARD_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE LIMIT_PROFILE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE USM_PWD_EXPRESSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE USM_POLICY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE USM_USER_GROUP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE USM_GROUP_PERMISSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE CARD_ACCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE BIZ_PROCESS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE BIZ_PROCESS_STATES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE BIZ_PROCESS_ASSEMBLY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- ========== 2. ADD ID COLUMN AND BACKFILL (idempotent: skip if column exists) ==========
-- RESPONSE_CODE
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RESPONSE_CODE ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE RESPONSE_CODE SET ID = RESPONSE_CODE_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RESPONSE_CODE MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- ACCOUNT_STATUS
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_STATUS ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE ACCOUNT_STATUS SET ID = ACCOUNT_STATUS_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_STATUS MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- ACCOUNT_TYPE
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_TYPE ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE ACCOUNT_TYPE SET ID = ACCOUNT_TYPE_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_TYPE MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- USM_PERMISSION
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PERMISSION ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE USM_PERMISSION SET ID = USM_PERMISSION_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PERMISSION MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- USM_USER
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE USM_USER SET ID = USM_USER_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- CARD_STATUS
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_STATUS ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE CARD_STATUS SET ID = CARD_STATUS_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_STATUS MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- CARD_PRODUCT
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCT ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE CARD_PRODUCT SET ID = CARD_PRODUCT_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCT MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- CARD_PRODUCTION_STATUS
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCTION_STATUS ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE CARD_PRODUCTION_STATUS SET ID = CARD_PRODUCTION_STATUS_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCTION_STATUS MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- USM_GROUP (referenced by USM_USER_GROUP, USM_GROUP_PERMISSION)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE USM_GROUP SET ID = USM_GROUP_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- BRANCH (referenced by CARD, CARD_REQUEST, ACCOUNT)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BRANCH ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE BRANCH SET ID = BRANCH_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BRANCH MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- CARD_TYPE (referenced by CARD, CARD_REQUEST; has FK to CARD_PRODUCT)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE CARD_TYPE SET ID = CARD_TYPE_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- LIMIT_PROFILE
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE LIMIT_PROFILE ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE LIMIT_PROFILE SET ID = LIMIT_PROFILE_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE LIMIT_PROFILE MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- USM_PWD_EXPRESSION
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PWD_EXPRESSION ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE USM_PWD_EXPRESSION SET ID = USM_PWD_EXPRESSION_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PWD_EXPRESSION MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- USM_POLICY
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_POLICY ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE USM_POLICY SET ID = USM_POLICY_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_POLICY MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- ACCOUNT
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD ACCOUNT_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE ACCOUNT SET ACCOUNT_ID = ACCOUNT_SEQ.NEXTVAL WHERE ACCOUNT_ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT MODIFY ACCOUNT_ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- USM_USER_GROUP (junction)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER_GROUP ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE USM_USER_GROUP SET ID = USM_USER_GROUP_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER_GROUP MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- USM_GROUP_PERMISSION (junction)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP_PERMISSION ADD ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE USM_GROUP_PERMISSION SET ID = USM_GROUP_PERMISSION_SEQ.NEXTVAL WHERE ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP_PERMISSION MODIFY ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/
-- CARD_ACCOUNT (junction; has CARD_ID from V13)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_ACCOUNT ADD CA_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE CARD_ACCOUNT SET CA_ID = CARD_ACCOUNT_SEQ.NEXTVAL WHERE CA_ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_ACCOUNT MODIFY CA_ID NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF; END;
/

-- ========== 3. ADD _ID COLUMNS ON CHILD TABLES AND BACKFILL (idempotent) ==========
-- CARD: BRANCH_ID, CARD_TYPE_ID, CARD_PRODUCT_ID, CARD_STATUS_ID, CARD_PROD_STATUS_ID, LIMIT_PROFILE_ID
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD BRANCH_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CARD_TYPE_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CARD_PRODUCT_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CARD_STATUS_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CARD_PRODUCTION_STATUS_REF_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD LIMIT_PROFILE_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE CARD c SET BRANCH_ID = (SELECT b.ID FROM BRANCH b WHERE b.BRANCH_CODE = c.BRANCH_CODE) WHERE c.BRANCH_CODE IS NOT NULL AND c.BRANCH_ID IS NULL;
UPDATE CARD c SET CARD_TYPE_ID = (SELECT t.ID FROM CARD_TYPE t WHERE t.CARD_TYPE_CODE = c.CARD_TYPE_CODE) WHERE c.CARD_TYPE_CODE IS NOT NULL AND c.CARD_TYPE_ID IS NULL;
UPDATE CARD c SET CARD_PRODUCT_ID = (SELECT p.ID FROM CARD_PRODUCT p WHERE p.PRODUCT_CODE = c.PRODUCT_CODE) WHERE c.PRODUCT_CODE IS NOT NULL AND c.CARD_PRODUCT_ID IS NULL;
UPDATE CARD c SET CARD_STATUS_ID = (SELECT s.ID FROM CARD_STATUS s WHERE s.CARD_STATUS_CODE = c.CARD_STATUS_CODE) WHERE c.CARD_STATUS_CODE IS NOT NULL AND c.CARD_STATUS_ID IS NULL;
UPDATE CARD c SET CARD_PRODUCTION_STATUS_REF_ID = (SELECT s.ID FROM CARD_PRODUCTION_STATUS s WHERE s.CARD_PROD_STATUS_ID = c.CARD_PROD_STATUS_ID) WHERE c.CARD_PROD_STATUS_ID IS NOT NULL AND c.CARD_PRODUCTION_STATUS_REF_ID IS NULL;
UPDATE CARD c SET LIMIT_PROFILE_ID = (SELECT l.ID FROM LIMIT_PROFILE l WHERE l.PROFILE_CODE = c.LIMIT_PROFILE) WHERE c.LIMIT_PROFILE IS NOT NULL AND c.LIMIT_PROFILE_ID IS NULL;

-- CARD_REQUEST: BRANCH_ID, CARD_TYPE_ID, CARD_PRODUCT_ID
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_REQUEST ADD BRANCH_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_REQUEST ADD CARD_TYPE_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_REQUEST ADD CARD_PRODUCT_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE CARD_REQUEST r SET BRANCH_ID = (SELECT b.ID FROM BRANCH b WHERE b.BRANCH_CODE = r.BRANCH_CODE) WHERE r.BRANCH_CODE IS NOT NULL AND r.BRANCH_ID IS NULL;
UPDATE CARD_REQUEST r SET CARD_TYPE_ID = (SELECT t.ID FROM CARD_TYPE t WHERE t.CARD_TYPE_CODE = r.CARD_TYPE_CODE) WHERE r.CARD_TYPE_CODE IS NOT NULL AND r.CARD_TYPE_ID IS NULL;
UPDATE CARD_REQUEST r SET CARD_PRODUCT_ID = (SELECT p.ID FROM CARD_PRODUCT p WHERE p.PRODUCT_CODE = r.PRODUCT_CODE) WHERE r.PRODUCT_CODE IS NOT NULL AND r.CARD_PRODUCT_ID IS NULL;

-- ACCOUNT: ACCOUNT_TYPE_ID, ACCOUNT_STATUS_ID, BRANCH_ID, LIMIT_PROFILE_ID
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD ACCOUNT_TYPE_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD ACCOUNT_STATUS_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD BRANCH_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD LIMIT_PROFILE_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE ACCOUNT a SET ACCOUNT_TYPE_ID = (SELECT t.ID FROM ACCOUNT_TYPE t WHERE t.ACCT_TYPE_CODE = a.ACCT_TYPE_CODE) WHERE a.ACCT_TYPE_CODE IS NOT NULL AND a.ACCOUNT_TYPE_ID IS NULL;
UPDATE ACCOUNT a SET ACCOUNT_STATUS_ID = (SELECT s.ID FROM ACCOUNT_STATUS s WHERE s.ACCT_STATUS_CODE = a.ACCT_STATUS_CODE) WHERE a.ACCT_STATUS_CODE IS NOT NULL AND a.ACCOUNT_STATUS_ID IS NULL;
UPDATE ACCOUNT a SET BRANCH_ID = (SELECT b.ID FROM BRANCH b WHERE b.BRANCH_CODE = a.BRANCH_CODE) WHERE a.BRANCH_CODE IS NOT NULL AND a.BRANCH_ID IS NULL;
UPDATE ACCOUNT a SET LIMIT_PROFILE_ID = (SELECT l.ID FROM LIMIT_PROFILE l WHERE l.PROFILE_CODE = a.LIMIT_PROFILE) WHERE a.LIMIT_PROFILE IS NOT NULL AND a.LIMIT_PROFILE_ID IS NULL;

-- CARD_ACCOUNT: ACCOUNT_ID (FK to ACCOUNT.ACCOUNT_ID)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_ACCOUNT ADD ACCOUNT_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE CARD_ACCOUNT ca SET ACCOUNT_ID = (SELECT a.ACCOUNT_ID FROM ACCOUNT a WHERE a.ACCOUNT_NUM = ca.ACCOUNT_NUM) WHERE ca.ACCOUNT_NUM IS NOT NULL AND ca.ACCOUNT_ID IS NULL;

-- ========== 4. DROP OLD FK CONSTRAINTS (before changing PKs, idempotent) ==========
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD DROP CONSTRAINT FK_CARD_BRANCH'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD DROP CONSTRAINT FK_CARD_STATUS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD DROP CONSTRAINT FK_CARD_PROD_STATUS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_REQUEST DROP CONSTRAINT FK_CARD_REQ_TYPE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_REQUEST DROP CONSTRAINT FK_CARD_REQ_PRODUCT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_ACCOUNT DROP CONSTRAINT FK_CARD_ACCT_ACCOUNT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_ACCOUNT DROP CONSTRAINT FK_CARD_ACCT_CARD'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/

-- ========== 5. DROP OLD PKs AND ADD NEW PKs + UNIQUE ON FORMER KEYS ==========
-- Drop FKs that reference USM_PERMISSION, USM_USER, USM_GROUP (must be before dropping their PKs)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP_PERMISSION DROP CONSTRAINT FK_UGP_GROUP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP_PERMISSION DROP CONSTRAINT FK_UGP_PERM'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER_GROUP DROP CONSTRAINT FK_UUG_GROUP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER_GROUP DROP CONSTRAINT FK_UUG_USER'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
-- RESPONSE_CODE
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RESPONSE_CODE DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RESPONSE_CODE ADD CONSTRAINT PK_RESPONSE_CODE PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RESPONSE_CODE ADD CONSTRAINT UK_RESPONSE_CODE_CODE UNIQUE (CODE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- ACCOUNT_STATUS
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_STATUS DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_STATUS ADD CONSTRAINT PK_ACCOUNT_STATUS PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_STATUS ADD CONSTRAINT UK_ACCOUNT_STATUS_CODE UNIQUE (ACCT_STATUS_CODE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- ACCOUNT_TYPE
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_TYPE DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_TYPE ADD CONSTRAINT PK_ACCOUNT_TYPE PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT_TYPE ADD CONSTRAINT UK_ACCOUNT_TYPE_CODE UNIQUE (ACCT_TYPE_CODE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- USM_PERMISSION
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PERMISSION DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PERMISSION ADD CONSTRAINT PK_USM_PERMISSION PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PERMISSION ADD CONSTRAINT UK_USM_PERMISSION_ID_CODE UNIQUE (PERMISSION_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- USM_USER
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER ADD CONSTRAINT PK_USM_USER PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER ADD CONSTRAINT UK_USM_USER_LOGIN_ID UNIQUE (LOGIN_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- CARD_STATUS
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_STATUS DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_STATUS ADD CONSTRAINT PK_CARD_STATUS PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_STATUS ADD CONSTRAINT UK_CARD_STATUS_CODE UNIQUE (CARD_STATUS_CODE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- CARD_PRODUCT
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCT DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCT ADD CONSTRAINT PK_CARD_PRODUCT PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCT ADD CONSTRAINT UK_CARD_PRODUCT_CODE UNIQUE (PRODUCT_CODE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- CARD_PRODUCTION_STATUS
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCTION_STATUS DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCTION_STATUS ADD CONSTRAINT PK_CARD_PRODUCTION_STATUS PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_PRODUCTION_STATUS ADD CONSTRAINT UK_CARD_PROD_STATUS_CODE UNIQUE (CARD_PROD_STATUS_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- CARD_TYPE (has FK to CARD_PRODUCT - drop it first)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE DROP CONSTRAINT FK_CARD_TYPE_PRODUCT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE ADD CONSTRAINT PK_CARD_TYPE PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE ADD CONSTRAINT UK_CARD_TYPE_CODE UNIQUE (CARD_TYPE_CODE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE ADD PRODUCT_ID NUMBER(19)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
UPDATE CARD_TYPE t SET PRODUCT_ID = (SELECT p.ID FROM CARD_PRODUCT p WHERE p.PRODUCT_CODE = t.PRODUCT_CODE) WHERE t.PRODUCT_CODE IS NOT NULL AND t.PRODUCT_ID IS NULL;
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_TYPE ADD CONSTRAINT FK_CARD_TYPE_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES CARD_PRODUCT(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
-- USM_GROUP (FKs already dropped at start of section 5)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP ADD CONSTRAINT PK_USM_GROUP PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP ADD CONSTRAINT UK_USM_GROUP_ID UNIQUE (GROUP_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- BRANCH
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BRANCH DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BRANCH ADD CONSTRAINT PK_BRANCH PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BRANCH ADD CONSTRAINT UK_BRANCH_CODE UNIQUE (BRANCH_CODE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- LIMIT_PROFILE
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE LIMIT_PROFILE DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE LIMIT_PROFILE ADD CONSTRAINT PK_LIMIT_PROFILE PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE LIMIT_PROFILE ADD CONSTRAINT UK_LIMIT_PROFILE_CODE UNIQUE (PROFILE_CODE)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- USM_PWD_EXPRESSION
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PWD_EXPRESSION DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PWD_EXPRESSION ADD CONSTRAINT PK_USM_PWD_EXPRESSION PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_PWD_EXPRESSION ADD CONSTRAINT UK_USM_PWD_EXP_ID UNIQUE (PWD_EXP_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- USM_POLICY
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_POLICY DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_POLICY ADD CONSTRAINT PK_USM_POLICY PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_POLICY ADD CONSTRAINT UK_USM_POLICY_ID UNIQUE (POLICY_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- Re-add FKs for USM_USER_GROUP and USM_GROUP_PERMISSION (reference unique GROUP_ID, LOGIN_ID, PERMISSION_ID)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER_GROUP ADD CONSTRAINT FK_UUG_GROUP FOREIGN KEY (GROUP_ID) REFERENCES USM_GROUP(GROUP_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER_GROUP ADD CONSTRAINT FK_UUG_USER FOREIGN KEY (LOGIN_ID) REFERENCES USM_USER(LOGIN_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP_PERMISSION ADD CONSTRAINT FK_UGP_GROUP FOREIGN KEY (GROUP_ID) REFERENCES USM_GROUP(GROUP_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP_PERMISSION ADD CONSTRAINT FK_UGP_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES USM_PERMISSION(PERMISSION_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
-- USM_USER_GROUP: new PK on ID, unique on (GROUP_ID, LOGIN_ID)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER_GROUP DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER_GROUP ADD CONSTRAINT PK_USM_USER_GROUP PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_USER_GROUP ADD CONSTRAINT UK_USM_USER_GROUP UNIQUE (GROUP_ID, LOGIN_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- USM_GROUP_PERMISSION: new PK on ID, unique on (GROUP_ID, PERMISSION_ID)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP_PERMISSION DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP_PERMISSION ADD CONSTRAINT PK_USM_GROUP_PERMISSION PRIMARY KEY (ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE USM_GROUP_PERMISSION ADD CONSTRAINT UK_USM_GROUP_PERMISSION UNIQUE (GROUP_ID, PERMISSION_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- ACCOUNT: new PK on ACCOUNT_ID, unique on ACCOUNT_NUM
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD CONSTRAINT UK_ACCOUNT_NUM UNIQUE (ACCOUNT_NUM)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/
-- CARD_ACCOUNT: new PK on CA_ID, unique on (CARD_ID, ACCOUNT_NUM); keep FK to ACCOUNT(ACCOUNT_ID)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_ACCOUNT DROP PRIMARY KEY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2273 AND SQLCODE != -2443 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_ACCOUNT ADD CONSTRAINT PK_CARD_ACCOUNT PRIMARY KEY (CA_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_ACCOUNT ADD CONSTRAINT UK_CARD_ACCOUNT_CARD_ACCT UNIQUE (CARD_ID, ACCOUNT_NUM)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 AND SQLCODE != -2261 THEN RAISE; END IF; END;
/

-- ========== 6. ADD NEW FK CONSTRAINTS (after parent tables have PK on ID, idempotent) ==========
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CONSTRAINT FK_CARD_BRANCH_ID FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CONSTRAINT FK_CARD_CARD_TYPE_ID FOREIGN KEY (CARD_TYPE_ID) REFERENCES CARD_TYPE(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CONSTRAINT FK_CARD_CARD_PRODUCT_ID FOREIGN KEY (CARD_PRODUCT_ID) REFERENCES CARD_PRODUCT(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CONSTRAINT FK_CARD_CARD_STATUS_ID FOREIGN KEY (CARD_STATUS_ID) REFERENCES CARD_STATUS(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CONSTRAINT FK_CARD_CARD_PROD_STATUS_REF FOREIGN KEY (CARD_PRODUCTION_STATUS_REF_ID) REFERENCES CARD_PRODUCTION_STATUS(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD ADD CONSTRAINT FK_CARD_LIMIT_PROFILE_ID FOREIGN KEY (LIMIT_PROFILE_ID) REFERENCES LIMIT_PROFILE(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_REQUEST ADD CONSTRAINT FK_CARD_REQ_BRANCH_ID FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_REQUEST ADD CONSTRAINT FK_CARD_REQ_CARD_TYPE_ID FOREIGN KEY (CARD_TYPE_ID) REFERENCES CARD_TYPE(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_REQUEST ADD CONSTRAINT FK_CARD_REQ_CARD_PRODUCT_ID FOREIGN KEY (CARD_PRODUCT_ID) REFERENCES CARD_PRODUCT(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_ACCOUNT_TYPE_ID FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_ACCOUNT_STATUS_ID FOREIGN KEY (ACCOUNT_STATUS_ID) REFERENCES ACCOUNT_STATUS(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_BRANCH_ID FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_LIMIT_PROFILE_ID FOREIGN KEY (LIMIT_PROFILE_ID) REFERENCES LIMIT_PROFILE(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CARD_ACCOUNT ADD CONSTRAINT FK_CARD_ACCT_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2260 THEN RAISE; END IF; END;
/

COMMIT;
