-- Update branch codes from text to numeric format
-- MAIN -> 0001

UPDATE CARD SET BRANCH_CODE = '0001' WHERE BRANCH_CODE = 'MAIN';
UPDATE CARD_REQUEST SET BRANCH_CODE = '0001' WHERE BRANCH_CODE = 'MAIN';
UPDATE ACCOUNT SET BRANCH_CODE = '0001' WHERE BRANCH_CODE = 'MAIN';
UPDATE BRANCH SET BRANCH_CODE = '0001' WHERE BRANCH_CODE = 'MAIN';

COMMIT;
