-- Add EXPORTED status to CARD_PRODUCTION_STATUS table
INSERT INTO CARD_PRODUCTION_STATUS (CARD_PROD_STATUS_ID, CARD_PROD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'EXPORTED', 'Exported to Bureau', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_PRODUCTION_STATUS WHERE CARD_PROD_STATUS_ID = 'EXPORTED');

COMMIT;
