-- Update card production status codes to numeric format
-- 001 = Issued (card generated, not yet exported)
-- 002 = Exported (export file generated and sent to bureau)

UPDATE CARD_PRODUCTION_STATUS SET CARD_PROD_STATUS_ID = '001' WHERE CARD_PROD_STATUS_ID = 'ISSUED';
UPDATE CARD_PRODUCTION_STATUS SET CARD_PROD_STATUS_ID = '002' WHERE CARD_PROD_STATUS_ID = 'EXPORTED';
UPDATE CARD_PRODUCTION_STATUS SET CARD_PROD_STATUS_ID = '000' WHERE CARD_PROD_STATUS_ID = 'PENDING';

-- Update any existing cards that already have these statuses
UPDATE CARD SET CARD_PROD_STATUS_ID = '001' WHERE CARD_PROD_STATUS_ID = 'ISSUED';
UPDATE CARD SET CARD_PROD_STATUS_ID = '002' WHERE CARD_PROD_STATUS_ID = 'EXPORTED';
UPDATE CARD SET CARD_PROD_STATUS_ID = '000' WHERE CARD_PROD_STATUS_ID = 'PENDING';

COMMIT;
