-- V19: Seed roles (USM_GROUP) and permissions (USM_PERMISSION) and map them

-- ===== ROLES (USM_GROUP) =====
INSERT INTO USM_GROUP (ID, GROUP_ID, GROUP_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_SEQ.NEXTVAL, 'ADMIN', 'Administrator', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP WHERE GROUP_ID = 'ADMIN');

INSERT INTO USM_GROUP (ID, GROUP_ID, GROUP_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_SEQ.NEXTVAL, 'CARD_OPERATOR', 'Card Operator', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP WHERE GROUP_ID = 'CARD_OPERATOR');

INSERT INTO USM_GROUP (ID, GROUP_ID, GROUP_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_SEQ.NEXTVAL, 'CARD_VIEWER', 'Card Viewer', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP WHERE GROUP_ID = 'CARD_VIEWER');

INSERT INTO USM_GROUP (ID, GROUP_ID, GROUP_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_SEQ.NEXTVAL, 'MANAGER', 'Housekeeping Manager', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP WHERE GROUP_ID = 'MANAGER');

INSERT INTO USM_GROUP (ID, GROUP_ID, GROUP_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_SEQ.NEXTVAL, 'SECURITY_MANAGER', 'Security Manager', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP WHERE GROUP_ID = 'SECURITY_MANAGER');

-- ===== PERMISSIONS (USM_PERMISSION) =====
-- Card permissions
INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'VIEW_CARDS', 'View Cards', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'VIEW_CARDS');

INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'CREATE_CARD_REQUEST', 'Create Card Request', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'CREATE_CARD_REQUEST');

INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'APPROVE_CARD', 'Approve and Generate Card', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'APPROVE_CARD');

INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'EXPORT_CARD', 'Export Cards to Bureau', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'EXPORT_CARD');

INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'CLOSE_CARD', 'Close Card', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'CLOSE_CARD');

INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'REPLACE_CARD', 'Replace Card', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'REPLACE_CARD');

INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'CHANGE_CARD_TYPE', 'Change Card Type', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'CHANGE_CARD_TYPE');

-- User permissions
INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'VIEW_USERS', 'View Users', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'VIEW_USERS');

INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'MANAGE_USERS', 'Create/Update/Delete Users', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'MANAGE_USERS');

-- Role permissions
INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'VIEW_ROLES', 'View Roles', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'VIEW_ROLES');

INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'MANAGE_ROLES', 'Create/Update/Delete Roles', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'MANAGE_ROLES');

-- Housekeeping permissions
INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'VIEW_HOUSEKEEPING', 'View Housekeeping Data', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'VIEW_HOUSEKEEPING');

INSERT INTO USM_PERMISSION (ID, PERMISSION_ID, PERMISSION_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_PERMISSION_SEQ.NEXTVAL, 'MANAGE_HOUSEKEEPING', 'Create/Update/Delete Housekeeping Data', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_PERMISSION WHERE PERMISSION_ID = 'MANAGE_HOUSEKEEPING');

-- ===== ROLE-PERMISSION MAPPING (USM_GROUP_PERMISSION) =====

-- ADMIN gets all permissions
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'VIEW_CARDS', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'VIEW_CARDS');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'CREATE_CARD_REQUEST', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'CREATE_CARD_REQUEST');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'APPROVE_CARD', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'APPROVE_CARD');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'EXPORT_CARD', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'EXPORT_CARD');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'CLOSE_CARD', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'CLOSE_CARD');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'REPLACE_CARD', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'REPLACE_CARD');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'CHANGE_CARD_TYPE', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'CHANGE_CARD_TYPE');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'VIEW_USERS', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'VIEW_USERS');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'MANAGE_USERS', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'MANAGE_USERS');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'VIEW_ROLES', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'VIEW_ROLES');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'MANAGE_ROLES', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'MANAGE_ROLES');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'VIEW_HOUSEKEEPING', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'VIEW_HOUSEKEEPING');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'ADMIN', 'MANAGE_HOUSEKEEPING', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'ADMIN' AND PERMISSION_ID = 'MANAGE_HOUSEKEEPING');

-- CARD_OPERATOR permissions
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'CARD_OPERATOR', 'VIEW_CARDS', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'CARD_OPERATOR' AND PERMISSION_ID = 'VIEW_CARDS');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'CARD_OPERATOR', 'CREATE_CARD_REQUEST', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'CARD_OPERATOR' AND PERMISSION_ID = 'CREATE_CARD_REQUEST');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'CARD_OPERATOR', 'APPROVE_CARD', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'CARD_OPERATOR' AND PERMISSION_ID = 'APPROVE_CARD');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'CARD_OPERATOR', 'EXPORT_CARD', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'CARD_OPERATOR' AND PERMISSION_ID = 'EXPORT_CARD');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'CARD_OPERATOR', 'CLOSE_CARD', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'CARD_OPERATOR' AND PERMISSION_ID = 'CLOSE_CARD');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'CARD_OPERATOR', 'REPLACE_CARD', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'CARD_OPERATOR' AND PERMISSION_ID = 'REPLACE_CARD');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'CARD_OPERATOR', 'CHANGE_CARD_TYPE', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'CARD_OPERATOR' AND PERMISSION_ID = 'CHANGE_CARD_TYPE');

-- CARD_VIEWER permissions (read only)
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'CARD_VIEWER', 'VIEW_CARDS', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'CARD_VIEWER' AND PERMISSION_ID = 'VIEW_CARDS');

-- MANAGER permissions
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'MANAGER', 'VIEW_HOUSEKEEPING', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'MANAGER' AND PERMISSION_ID = 'VIEW_HOUSEKEEPING');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'MANAGER', 'MANAGE_HOUSEKEEPING', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'MANAGER' AND PERMISSION_ID = 'MANAGE_HOUSEKEEPING');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'MANAGER', 'VIEW_CARDS', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'MANAGER' AND PERMISSION_ID = 'VIEW_CARDS');

-- SECURITY_MANAGER permissions
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'SECURITY_MANAGER', 'VIEW_USERS', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'SECURITY_MANAGER' AND PERMISSION_ID = 'VIEW_USERS');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'SECURITY_MANAGER', 'MANAGE_USERS', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'SECURITY_MANAGER' AND PERMISSION_ID = 'MANAGE_USERS');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'SECURITY_MANAGER', 'VIEW_ROLES', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'SECURITY_MANAGER' AND PERMISSION_ID = 'VIEW_ROLES');
INSERT INTO USM_GROUP_PERMISSION (ID, GROUP_ID, PERMISSION_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_GROUP_PERMISSION_SEQ.NEXTVAL, 'SECURITY_MANAGER', 'MANAGE_ROLES', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_GROUP_PERMISSION WHERE GROUP_ID = 'SECURITY_MANAGER' AND PERMISSION_ID = 'MANAGE_ROLES');

-- Assign ADMIN role to admin user
INSERT INTO USM_USER_GROUP (ID, LOGIN_ID, GROUP_ID, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT USM_USER_GROUP_SEQ.NEXTVAL, 'admin', 'ADMIN', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USM_USER_GROUP WHERE LOGIN_ID = 'admin' AND GROUP_ID = 'ADMIN');

COMMIT;
