-- Oracle 19c schema for Card Management System (existing entities)
-- Run via Flyway on first start when spring.datasource.url points to your Oracle DB

-- BIZ_PROCESS (no FK)
CREATE TABLE BIZ_PROCESS (
  BIZPROCESSID NUMBER(19) NOT NULL PRIMARY KEY,
  BIZPROCESSNAME VARCHAR2(255),
  CHANNELID NUMBER(19),
  MESSAGETYPE NUMBER(10),
  DESCRIPTION VARCHAR2(500),
  ACTION_TYPE NUMBER(10)
);

-- BIZ_PROCESS_STATES
CREATE TABLE BIZ_PROCESS_STATES (
  PROCESSSTATEID NUMBER(19) NOT NULL PRIMARY KEY,
  CLASSNAME VARCHAR2(255),
  METHODNAME VARCHAR2(255),
  BIZPROCESSID NUMBER(19),
  NEXTSEQNUM_SUCCESS NUMBER(10),
  NEXTSEQNUM_FAIL NUMBER(10),
  SEQUENCENUMBER NUMBER(10),
  CONSTRAINT FK_BPS_BIZPROCESS FOREIGN KEY (BIZPROCESSID) REFERENCES BIZ_PROCESS(BIZPROCESSID)
);

-- BIZ_PROCESS_ASSEMBLY
CREATE TABLE BIZ_PROCESS_ASSEMBLY (
  ASSEMBLYID NUMBER(19) NOT NULL PRIMARY KEY,
  ASSEMBLYNAME VARCHAR2(255),
  FACADENAME VARCHAR2(255),
  BINARYPATH VARCHAR2(500),
  BINARYVERSION VARCHAR2(50)
);

-- USM_PERMISSION
CREATE TABLE USM_PERMISSION (
  PERMISSION_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  PER_PARENT_ID VARCHAR2(50),
  PERMISSION_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  PERMISSION_TYPE VARCHAR2(50),
  CAN_CREATE NUMBER(1),
  CAN_UPDATE NUMBER(1),
  CAN_DELETE NUMBER(1),
  IS_AUDITING_ALLOWED NUMBER(1),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  FIELD_TYPE VARCHAR2(50),
  SEQUENCE NUMBER(10),
  LOCATION VARCHAR2(255),
  VIEW_NAME VARCHAR2(255),
  CSS_CLASS_NAME VARCHAR2(255),
  TABLE_NAME VARCHAR2(255),
  TRAN_CODE VARCHAR2(50),
  IS_VISIBLE NUMBER(1)
);

-- USM_USER
CREATE TABLE USM_USER (
  LOGIN_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  PASSWORD VARCHAR2(500),
  FULL_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  PREFERED_CULTURE VARCHAR2(20),
  IS_ACTIVE NUMBER(1),
  WHEN_DELETED TIMESTAMP,
  POLICY_ID VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  IS_LOGGED_IN NUMBER(1),
  WINDOWS_LOGGEDIN_BY VARCHAR2(50),
  LAST_RESPONSE_AT TIMESTAMP,
  IS_RESET_REQUIRED VARCHAR2(5),
  PWD_RETRY_COUNT NUMBER(10),
  SUPPORT_LEVEL_ID NUMBER(10),
  EMAIL_ADDRESS VARCHAR2(255),
  CORPORATE_ID VARCHAR2(50),
  APP_ID VARCHAR2(50),
  PWD_UPDATED_ON TIMESTAMP,
  RESET_PASSWORD NUMBER(10)
);

-- ACCOUNT_STATUS
CREATE TABLE ACCOUNT_STATUS (
  ACCT_STATUS_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  ACCT_STATUS_NAME VARCHAR2(255),
  DESCRIPTION VARCHAR2(500),
  IS_TRAN_ALLOWED NUMBER(1),
  IS_LINKING_ALLOWED NUMBER(1),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  ISO_CODE VARCHAR2(20),
  IS_ACTIVE NUMBER(1),
  GROUP_ID VARCHAR2(50),
  MAPPING_ID VARCHAR2(50),
  OTHER_LANG_NAME VARCHAR2(255)
);

-- ACCOUNT_TYPE
CREATE TABLE ACCOUNT_TYPE (
  ACCT_TYPE_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  ACCT_TYPE_NAME VARCHAR2(255),
  IS_FROM NUMBER(1),
  IS_TO NUMBER(1),
  ISO_CODE VARCHAR2(20),
  OTHER_LANG_NAME VARCHAR2(255),
  GROUP_ID VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  WINDOWS_CREATED_BY VARCHAR2(50),
  WINDOWS_UPDATED_BY VARCHAR2(50),
  MACHINE_NAME VARCHAR2(255),
  CORPORATE_ID VARCHAR2(50),
  IS_LINKING_ALLOWED NUMBER(10)
);

-- COUNTRY
CREATE TABLE COUNTRY (
  COUNTRY_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  ISO_DIGIT_CODE VARCHAR2(20),
  COUNTRY_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  MAPPING_ID VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  IS_TRAN_ALLOWED NUMBER(1),
  SWITCH_COUNTRY_CODE VARCHAR2(20)
);

-- RESPONSE_CODE
CREATE TABLE RESPONSE_CODE (
  CODE VARCHAR2(20) NOT NULL PRIMARY KEY,
  SHORT_DESCRIPTION VARCHAR2(500),
  FULL_DESCRIPTION VARCHAR2(1000),
  ALERT_TYPE VARCHAR2(50),
  HTTP_RESPONSE_CODE VARCHAR2(10)
);

-- Seed: minimal BIZ_PROCESS + BIZ_PROCESS_STATES for AccountStatusManager (channel 1, messageType 1)
INSERT INTO BIZ_PROCESS (BIZPROCESSID, BIZPROCESSNAME, CHANNELID, MESSAGETYPE, DESCRIPTION, ACTION_TYPE)
VALUES (1, 'AccountStatusProcess', 1, 1, 'Prepaid account status', 1);

INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (1, 'AccountStatusManager', 'CreateAccountStatus', 1, NULL, NULL, 1);

-- Seed: RESPONSE_CODE for Success and common errors
INSERT INTO RESPONSE_CODE (CODE, SHORT_DESCRIPTION, FULL_DESCRIPTION, ALERT_TYPE, HTTP_RESPONSE_CODE) VALUES ('200', 'Success', 'Operation completed successfully', 'success', '200');
INSERT INTO RESPONSE_CODE (CODE, SHORT_DESCRIPTION, FULL_DESCRIPTION, ALERT_TYPE, HTTP_RESPONSE_CODE) VALUES ('400', 'Bad Request', 'Invalid request', 'error', '400');
INSERT INTO RESPONSE_CODE (CODE, SHORT_DESCRIPTION, FULL_DESCRIPTION, ALERT_TYPE, HTTP_RESPONSE_CODE) VALUES ('404', 'Not Found', 'Resource not found', 'error', '404');
INSERT INTO RESPONSE_CODE (CODE, SHORT_DESCRIPTION, FULL_DESCRIPTION, ALERT_TYPE, HTTP_RESPONSE_CODE) VALUES ('409', 'Conflict', 'Resource already exists', 'warning', '409');
INSERT INTO RESPONSE_CODE (CODE, SHORT_DESCRIPTION, FULL_DESCRIPTION, ALERT_TYPE, HTTP_RESPONSE_CODE) VALUES ('500', 'Internal Server Error', 'An error occurred', 'error', '500');

-- Seed: one USM_USER for testing login (password: test123)
INSERT INTO USM_USER (LOGIN_ID, PASSWORD, FULL_NAME, IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, APP_ID)
VALUES ('admin', 'test123', 'Admin User', 1, SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system', 'CMS');

COMMIT;
