-- V20: Menu-based RBAC tables and seed data

-- ===== MENUS TABLE =====
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CMS_MENU (
    ID NUMBER(19) NOT NULL PRIMARY KEY,
    MENU_NAME VARCHAR2(100) NOT NULL,
    MENU_PATH VARCHAR2(255) NOT NULL,
    PARENT_MENU_ID NUMBER(19) NULL,
    MENU_ICON VARCHAR2(50),
    SORT_ORDER NUMBER(10) DEFAULT 0,
    STATUS CHAR(1) DEFAULT ''Y'',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE CMS_MENU_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- ===== ROLE_MENUS TABLE =====
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE CMS_ROLE_MENU (
    ID NUMBER(19) NOT NULL PRIMARY KEY,
    ROLE_CODE VARCHAR2(50) NOT NULL,
    MENU_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE CMS_ROLE_MENU_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- ===== SEED MENUS =====
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Dashboard', '/', 'pi-home', 1, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Cards', '/operations/cards', 'pi-credit-card', 2, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'New Card Request', '/card-production/new-request', 'pi-plus-circle', 3, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Card Requests', '/card-production/requests', 'pi-list', 4, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Card Generation', '/card-production/generation', 'pi-cog', 5, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Users', '/security/users', 'pi-users', 6, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Roles', '/security/roles', 'pi-shield', 7, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Permissions', '/security/permissions', 'pi-key', 8, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Branches', '/housekeeping/branches', 'pi-map-marker', 9, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Account Statuses', '/housekeeping/account-statuses', 'pi-info-circle', 10, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Account Types', '/housekeeping/account-types', 'pi-list', 11, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Products', '/housekeeping/products', 'pi-box', 12, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Card Types', '/housekeeping/card-types', 'pi-credit-card', 13, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Limit Profiles', '/housekeeping/limit-profiles', 'pi-wallet', 14, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Policies', '/housekeeping/policies', 'pi-file', 15, 'Y');
INSERT INTO CMS_MENU (ID, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, STATUS) VALUES (CMS_MENU_SEQ.NEXTVAL, 'Response Codes', '/housekeeping/response-codes', 'pi-code', 16, 'Y');

-- ===== ASSIGN ALL MENUS TO ADMIN =====
INSERT INTO CMS_ROLE_MENU (ID, ROLE_CODE, MENU_ID) SELECT CMS_ROLE_MENU_SEQ.NEXTVAL, 'ADMIN', ID FROM CMS_MENU;

-- ===== CARD_OPERATOR menus =====
INSERT INTO CMS_ROLE_MENU (ID, ROLE_CODE, MENU_ID) SELECT CMS_ROLE_MENU_SEQ.NEXTVAL, 'CARD_OPERATOR', ID FROM CMS_MENU WHERE MENU_PATH IN ('/', '/operations/cards', '/card-production/new-request', '/card-production/requests', '/card-production/generation');

-- ===== CARD_VIEWER menus =====
INSERT INTO CMS_ROLE_MENU (ID, ROLE_CODE, MENU_ID) SELECT CMS_ROLE_MENU_SEQ.NEXTVAL, 'CARD_VIEWER', ID FROM CMS_MENU WHERE MENU_PATH IN ('/', '/operations/cards');

-- ===== MANAGER menus =====
INSERT INTO CMS_ROLE_MENU (ID, ROLE_CODE, MENU_ID) SELECT CMS_ROLE_MENU_SEQ.NEXTVAL, 'MANAGER', ID FROM CMS_MENU WHERE MENU_PATH IN ('/', '/operations/cards', '/housekeeping/branches', '/housekeeping/account-statuses', '/housekeeping/account-types', '/housekeeping/products', '/housekeeping/card-types', '/housekeeping/limit-profiles', '/housekeeping/policies', '/housekeeping/response-codes');

-- ===== SECURITY_MANAGER menus =====
INSERT INTO CMS_ROLE_MENU (ID, ROLE_CODE, MENU_ID) SELECT CMS_ROLE_MENU_SEQ.NEXTVAL, 'SECURITY_MANAGER', ID FROM CMS_MENU WHERE MENU_PATH IN ('/', '/security/users', '/security/roles', '/security/permissions');

COMMIT;
