-- V22: Card usage / risk states (numeric codes) for CARD_STATUS lookup.
-- Uses MAX(ID)+1 so inserts succeed even if CARD_STATUS_SEQ is out of sync with existing rows.
-- Do not COMMIT here; Flyway runs the migration in a transaction.

INSERT INTO CARD_STATUS (ID, CARD_STATUS_CODE, CARD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CARD_STATUS), '001', 'Cold', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_STATUS WHERE CARD_STATUS_CODE = '001');

INSERT INTO CARD_STATUS (ID, CARD_STATUS_CODE, CARD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CARD_STATUS), '002', 'Warm', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_STATUS WHERE CARD_STATUS_CODE = '002');

INSERT INTO CARD_STATUS (ID, CARD_STATUS_CODE, CARD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CARD_STATUS), '003', 'Hot', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_STATUS WHERE CARD_STATUS_CODE = '003');
