-- V23: Re-seed card usage / risk states (001 Cold, 002 Warm, 003 Hot).
-- Use when rows were removed manually or V22 already applied and must not be re-run.
-- Idempotent: skips any code that already exists.

INSERT INTO CARD_STATUS (ID, CARD_STATUS_CODE, CARD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CARD_STATUS), '001', 'Cold', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_STATUS WHERE CARD_STATUS_CODE = '001');

INSERT INTO CARD_STATUS (ID, CARD_STATUS_CODE, CARD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CARD_STATUS), '002', 'Warm', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_STATUS WHERE CARD_STATUS_CODE = '002');

INSERT INTO CARD_STATUS (ID, CARD_STATUS_CODE, CARD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CARD_STATUS), '003', 'Hot', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_STATUS WHERE CARD_STATUS_CODE = '003');
