-- V25: Ensure ADMIN has access to all menus

INSERT INTO CMS_ROLE_MENU (ID, ROLE_CODE, MENU_ID, CREATED_AT)
SELECT CMS_ROLE_MENU_SEQ.NEXTVAL, 'ADMIN', m.ID, SYSTIMESTAMP
FROM CMS_MENU m
WHERE NOT EXISTS (
    SELECT 1
    FROM CMS_ROLE_MENU rm
    WHERE rm.ROLE_CODE = 'ADMIN'
      AND rm.MENU_ID = m.ID
);

COMMIT;
