-- V21: Audit log table for tracking all API calls
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE AUDIT_LOG (
    ID NUMBER(19) NOT NULL PRIMARY KEY,
    LOGIN_ID VARCHAR2(50),
    ACTION VARCHAR2(255),
    HTTP_METHOD VARCHAR2(10),
    API_PATH VARCHAR2(500),
    REQUEST_BODY CLOB,
    RESPONSE_STATUS VARCHAR2(20),
    ERROR_MESSAGE VARCHAR2(1000),
    IP_ADDRESS VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
COMMIT;
