-- AES-GCM ciphertext (base64) for CVV/iCVV needs more than VARCHAR2(20).
-- Track ciphertext also needs headroom beyond previous Base64-of-plaintext sizes.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CARD MODIFY (CVV VARCHAR2(256))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -904) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CARD MODIFY (CVV2 VARCHAR2(256))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -904) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CARD MODIFY (ICVV VARCHAR2(256))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -904) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CARD MODIFY (TRACK1_DATA VARCHAR2(1000))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -904) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CARD MODIFY (TRACK2_DATA VARCHAR2(1000))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -904) THEN RAISE; END IF;
END;
/
