-- Temporary login lock: after failed attempts, PWD_LOCKED_UNTIL holds unlock time.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE USM_USER ADD (PWD_LOCKED_UNTIL TIMESTAMP)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1430, -955) THEN RAISE; END IF;
END;
/
