-- Oracle 19c: USM and reference tables for auth and UserManager

CREATE TABLE USM_APPLICATION (
  APP_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  APP_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  APP_URL VARCHAR2(500),
  IS_SINGLE_LOGIN NUMBER(1),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  TOKEN_EXPIRY NUMBER(19)
);

CREATE TABLE USM_GROUP (
  GROUP_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  GROUP_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  IS_ACTIVE NUMBER(1),
  WHEN_DELETED TIMESTAMP,
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  HOME_PAGE VARCHAR2(255),
  IS_ADMIN NUMBER(1),
  FA_OPTION_ID VARCHAR2(50),
  APP_ID VARCHAR2(50),
  CORPORATE_CODE VARCHAR2(50),
  MERCHANT_CODE VARCHAR2(50),
  STORE_CODE VARCHAR2(50)
);

CREATE TABLE USM_USER_GROUP (
  GROUP_ID VARCHAR2(50) NOT NULL,
  LOGIN_ID VARCHAR2(50) NOT NULL,
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  PRIMARY KEY (GROUP_ID, LOGIN_ID),
  CONSTRAINT FK_UUG_GROUP FOREIGN KEY (GROUP_ID) REFERENCES USM_GROUP(GROUP_ID),
  CONSTRAINT FK_UUG_USER FOREIGN KEY (LOGIN_ID) REFERENCES USM_USER(LOGIN_ID)
);

CREATE TABLE USM_GROUP_PERMISSION (
  GROUP_ID VARCHAR2(50) NOT NULL,
  PERMISSION_ID VARCHAR2(50) NOT NULL,
  CAN_CREATE NUMBER(1),
  IS_AUDITING_ALLOWED NUMBER(1),
  CAN_UPDATE NUMBER(1),
  CAN_DELETE NUMBER(1),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  WINDOWS_UPDATED_BY VARCHAR2(50),
  WINDOWS_CREATED_BY VARCHAR2(50),
  MACHINE_NAME VARCHAR2(255),
  SEQUENCE NUMBER(10),
  APP_ID VARCHAR2(50),
  PRIMARY KEY (GROUP_ID, PERMISSION_ID),
  CONSTRAINT FK_UGP_GROUP FOREIGN KEY (GROUP_ID) REFERENCES USM_GROUP(GROUP_ID),
  CONSTRAINT FK_UGP_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES USM_PERMISSION(PERMISSION_ID)
);

CREATE TABLE BANK (
  BANK_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  SHORT_NAME VARCHAR2(100),
  RESERVED_1 VARCHAR2(255),
  NETWORK_ID NUMBER(10),
  IS_ACTIVE NUMBER(1),
  SWIFT_CODE VARCHAR2(50),
  BIC VARCHAR2(50),
  COUNTRY_CODE VARCHAR2(50),
  CURRENCY_CODE VARCHAR2(20),
  ADDRESS VARCHAR2(500),
  PHOTOGRAPH VARCHAR2(500),
  OTHER_LANG_NAME VARCHAR2(255)
);

CREATE TABLE CURRENCY (
  CURRENCY_CODE VARCHAR2(20) NOT NULL PRIMARY KEY,
  CURRENCY_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  ISO_CHAR_CODE VARCHAR2(10),
  CURRENCY_EDIT NUMBER(10),
  MAPPING_ID VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  IS_ACTIVE NUMBER(1),
  MNEMONIC_CODE VARCHAR2(20)
);

CREATE TABLE CITY (
  CITY_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  IS_ACTIVE NUMBER(1),
  COUNTRY_CODE VARCHAR2(50),
  OTHER_LANG_NAME VARCHAR2(255)
);

CREATE TABLE BRANCH (
  BRANCH_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  ENTITY_ID VARCHAR2(50),
  SWIFT_CODE VARCHAR2(50),
  BRANCH_NAME VARCHAR2(255),
  CITY_CODE VARCHAR2(50),
  COUNTRY_CODE VARCHAR2(50),
  OTHER_LANG_NAME VARCHAR2(255),
  BRIEF_NAME VARCHAR2(100),
  ADDRESS_1 VARCHAR2(500),
  ADDRESS_2 VARCHAR2(500),
  ZIP_CODE VARCHAR2(20),
  PHONE1 VARCHAR2(50),
  PHONE2 VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  CURRENCY_CODE VARCHAR2(20)
);

-- Optional: 401 for Unauthorized (used by auth/BLR)
INSERT INTO RESPONSE_CODE (CODE, SHORT_DESCRIPTION, FULL_DESCRIPTION, ALERT_TYPE, HTTP_RESPONSE_CODE)
SELECT '401', 'Unauthorized', 'Authentication required or invalid', 'error', '401' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM RESPONSE_CODE WHERE CODE = '401');

COMMIT;
