-- Oracle 19c: Batch 1 (core/ref), Batch 2 (audit/config), USM policy tables for Phase 1 DAL

-- Batch 1 - Core/ref
CREATE TABLE ACCOUNT (
  ACCOUNT_NUM VARCHAR2(50) NOT NULL PRIMARY KEY,
  ACCOUNT_TITLE VARCHAR2(255),
  ACCT_TYPE_CODE VARCHAR2(50),
  ACCT_STATUS_CODE VARCHAR2(50),
  BRANCH_CODE VARCHAR2(50),
  OPENED_DATE TIMESTAMP,
  LIMIT_PROFILE VARCHAR2(50),
  CURRENCY_CODE VARCHAR2(20),
  IS_JOINT NUMBER(1),
  CLOSED_DATE TIMESTAMP,
  CLOSED_REMARKS VARCHAR2(500),
  RESERVER_4 VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  IBAN VARCHAR2(100),
  IS_CLOSED NUMBER(1)
);

CREATE TABLE ACCOUNT_OFFICER (
  OFFICER_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  OTHER_LANG_NAME VARCHAR2(255),
  OFFICER_NAME VARCHAR2(255),
  BRANCH_CODE VARCHAR2(50),
  ADDRESS_1 VARCHAR2(500),
  EMAIL_ADDRESS VARCHAR2(255),
  ZIP_CODE VARCHAR2(20),
  COUNTRY_CODE VARCHAR2(50),
  CITY VARCHAR2(100),
  ADDRESS_2 VARCHAR2(500),
  RESERVED_1 VARCHAR2(255),
  RESERVED_2 VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE ACTION_TYPE (
  ACTION_TYPE_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  ACTION_TYPE_NAME VARCHAR2(255),
  IS_ACTIVE NUMBER(1),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);
//to make
CREATE TABLE APPLICATION_SEQUENCE (
  SEQUENCE_NAME VARCHAR2(100) NOT NULL PRIMARY KEY,
  MAX_VAL NUMBER(19),
  NEXT_VAL NUMBER(19),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE BANK_ENTITY (
  ENTITY_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  ENTITY_NAME VARCHAR2(255),
  COUNTRY_CODE VARCHAR2(50),
  CURRENCY_CODE VARCHAR2(20),
  OTHER_LANG_NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  COUNTRY_CODE_IBAN VARCHAR2(10),
  IBAN_LENGTH NUMBER(19)
);

CREATE TABLE BANK_SYSTEM (
  ENTITY_ID VARCHAR2(50) NOT NULL,
  SYSTEM_ID VARCHAR2(50) NOT NULL,
  SYSTEM_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  PRIMARY KEY (ENTITY_ID, SYSTEM_ID)
);

CREATE TABLE CHANNEL (
  CHANNEL_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  CHANNEL_NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE CACHE_ITEM_INFO (
  ITEM_NAME VARCHAR2(100) NOT NULL PRIMARY KEY,
  SQL_TYPE VARCHAR2(50),
  SQL_TEXT VARCHAR2(4000),
  PRIORITY NUMBER(10),
  LAST_UPDATED TIMESTAMP,
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  LOAD_ON_APP_START NUMBER(1),
  REFRESH_TIME_INTERVAL NUMBER(10)
);

CREATE TABLE COUNTER_VALUE (
  COUNTER_NAME VARCHAR2(100) NOT NULL,
  UNIQUE_ID VARCHAR2(50) NOT NULL,
  NEXT_VALUE NUMBER(19),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  PRIMARY KEY (COUNTER_NAME, UNIQUE_ID)
);

CREATE TABLE CUSTOMER_TYPE (
  CUST_TYPE_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  CUST_TYPE_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  IS_ACTIVE NUMBER(1),
  RESERVED_1 VARCHAR2(255)
);

CREATE TABLE DEVICE_FACTORY (
  DEVICE_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  DEVICE_NAME VARCHAR2(255),
  DEVICE_TYPE_CODE VARCHAR2(50),
  DEVICE_USAGE_CODE VARCHAR2(50),
  DEVICE_IP VARCHAR2(50),
  DEVICE_PORT NUMBER(10),
  IS_PRIMARY VARCHAR2(5),
  BRANCH_CODE VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  DEVICE_PROTOCOL VARCHAR2(50),
  IS_ACTIVE VARCHAR2(5),
  MSG_HEADER_LEN NUMBER(10),
  PAPER_LINE_FEEDS NUMBER(10)
);

CREATE TABLE DEVICE_TYPE (
  DEVICE_TYPE_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  DEVICE_TYPE_NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE DEVICE_USAGE (
  DEVICE_USAGE_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  DEVICE_USAGE_NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE GENDER (
  GENDER_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  GENDER_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  MAPPING_ID VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE INSTRUMENT (
  INSTRUMENT_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  INSTRUMENT_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE LANGUAGE (
  LANG_CODE VARCHAR2(20) NOT NULL PRIMARY KEY,
  LANG_NAME VARCHAR2(255),
  CULTURE_NAME VARCHAR2(50),
  MAPPING_ID VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  OTHER_LANG_NAME VARCHAR2(255)
);

CREATE TABLE META_COUNTER (
  COUNTER_NAME VARCHAR2(100) NOT NULL PRIMARY KEY,
  START_VALUE NUMBER(19),
  MAX_VALUE NUMBER(19),
  PREFIX_VALUE VARCHAR2(50),
  INCREMENT_BY VARCHAR2(20),
  IS_CYCLIC NUMBER(19),
  IMPL_CLASS VARCHAR2(255),
  FORMAT_EXP VARCHAR2(100),
  RESET_TYPE VARCHAR2(20),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  NEXT_VALUE NUMBER(19),
  UNIQUE_ID VARCHAR2(50)
);

CREATE TABLE MARITAL_STATUS (
  MARITAL_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  MARITAL_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  MAPPING_ID VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE NATIONALITY (
  NATIONALITY_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  NATIONALITY_NAME VARCHAR2(255),
  MAPPING_ID VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  IS_ACTIVE NUMBER(1)
);

CREATE TABLE OCCUPATION (
  OCCUPATION_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  OCCUPATION_TITLE VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE RELIGION (
  RELIGION_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  RELIGION_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  MAPPING_ID VARCHAR2(50),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE TITLE (
  TITLE_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  TITLE_NAME VARCHAR2(255)
);

CREATE TABLE TRANSACTION_GROUP (
  TRAN_GROUP_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  TRAN_GROUP_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE TRANSACTION_CODE (
  TRAN_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
  TRAN_GROUP_CODE VARCHAR2(50),
  TRAN_TYPE NUMBER(10),
  TRAN_NAME VARCHAR2(255),
  DESCRIPTION VARCHAR2(500),
  OTHER_LANG_NAME VARCHAR2(255),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  IS_POS_TRAN NUMBER(1),
  IS_EFT NUMBER(1),
  IS_OFFLINE NUMBER(1),
  IS_DC_API_ENABLED NUMBER(1)
);

-- Batch 2 - Audit/config
CREATE TABLE AUDIT_LOG_BATCH (
  ID NUMBER(19) NOT NULL PRIMARY KEY,
  ENTITY_ID VARCHAR2(50),
  APP_ID VARCHAR2(50),
  MODULE VARCHAR2(100),
  SCREEN VARCHAR2(100),
  ACTION VARCHAR2(50),
  MAKER VARCHAR2(50),
  MAKER_DATE TIMESTAMP,
  CHECKER VARCHAR2(50),
  CHECKER_DATE TIMESTAMP,
  STATUS VARCHAR2(20)
);

CREATE TABLE AUDIT_LOG_ENTITY (
  ID NUMBER(19) NOT NULL PRIMARY KEY,
  BATCH_ID NUMBER(19),
  NAME VARCHAR2(255),
  TABLE_KEY VARCHAR2(100),
  TABLE_NAME VARCHAR2(100),
  TABLE_OPERATION VARCHAR2(20)
);

CREATE TABLE AUDIT_LOG_FIELD (
  ID NUMBER(19) NOT NULL PRIMARY KEY,
  TABLE_ID NUMBER(19),
  FIELD_NAME VARCHAR2(100),
  OLD_VALUE VARCHAR2(4000),
  NEW_VALUE VARCHAR2(4000)
);

CREATE TABLE SCHEMA_METADATA (
  TABLE_NAME VARCHAR2(100) NOT NULL,
  FIELD_NAME VARCHAR2(100) NOT NULL,
  FIELD_DISPLAY_NAME VARCHAR2(255),
  IS_PRIMARY NUMBER(1),
  CREATED_ON TIMESTAMP,
  PRIMARY KEY (TABLE_NAME, FIELD_NAME)
);

CREATE TABLE SCHEMA_METADATA_TABLE (
  TABLE_NAME VARCHAR2(100) NOT NULL PRIMARY KEY,
  TABLE_DISPLAY_NAME VARCHAR2(255),
  TYPE VARCHAR2(50)
);

CREATE TABLE SEARCH_FILTER (
  FILTER_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  FILTER_NAME VARCHAR2(255),
  FILTER_TYPE VARCHAR2(50),
  FILTER_JSON VARCHAR2(4000),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

CREATE TABLE SEARCH_FILTER_BINDING (
  PERMISSION_ID VARCHAR2(50) NOT NULL,
  FILTER_ID VARCHAR2(50) NOT NULL,
  IS_MANDATORY NUMBER(10),
  SHOW_SEQUENCE NUMBER(10),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  PRIMARY KEY (PERMISSION_ID, FILTER_ID)
);

CREATE TABLE SYSTEM_CONFIGURATION (
  PARAM_TYPE VARCHAR2(50) NOT NULL,
  PARAM_NAME VARCHAR2(100) NOT NULL,
  PARAM_VALUE VARCHAR2(1000),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  PRIMARY KEY (PARAM_TYPE, PARAM_NAME)
);

CREATE TABLE REPORT_CONNECTION_STRING (
  REPORT_CON_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  NAME VARCHAR2(255),
  CONNECTION_STRING VARCHAR2(1000),
  PROVIDER VARCHAR2(100),
  APP_ID VARCHAR2(50)
);

-- USM policy (Phase 2 PasswordPolicyService)
CREATE TABLE USM_PWD_EXPRESSION (
  PWD_EXP_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  PWD_EXP_NAME VARCHAR2(255),
  PWD_EXPRESSION VARCHAR2(500),
  PWD_EXP_DESCRIPTION VARCHAR2(500)
);

CREATE TABLE USM_POLICY (
  POLICY_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  POLICY_NAME VARCHAR2(255),
  OTHER_LANG_NAME VARCHAR2(255),
  POLICY_DESCRIPTION VARCHAR2(500),
  TIME_EXPRESSION VARCHAR2(100),
  IS_AUTO_RESET NUMBER(1),
  IS_MULTI_LOGIN NUMBER(1),
  IS_DEFAULT NUMBER(1),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50),
  PWD_EXPIRY_PERIOD NUMBER(19),
  PWD_EXPIRY_NOTIFY_PERIOD NUMBER(19),
  PWD_RETRY_COUNT NUMBER(19),
  PWD_HISTORY_COUNT NUMBER(19),
  ACCOUNT_DISABLE_PERIOD NUMBER(19),
  IS_FIRST_RESET_REQUIRED NUMBER(1),
  IS_CYCLIC_PWD_ALLOWED NUMBER(1),
  PWD_EXP_ID VARCHAR2(50),
  PASSWORD_EXPRESSION VARCHAR2(500),
  PWD_EXPRESSION_WEAK VARCHAR2(500),
  PWD_EXPRESSION_NORMAL VARCHAR2(500),
  PWD_EXPRESSION_STRONG VARCHAR2(500),
  CAN_PWD_MATCH_LOGIN NUMBER(1),
  IS_COMMON_WORD_ALLOWED NUMBER(1),
  PASSWORD_EXPIRY_COUNT NUMBER(5)
);

CREATE TABLE USM_PWD_HISTORY (
  PWD_HISTORY_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
  LOGIN_ID VARCHAR2(50),
  PASSWORD VARCHAR2(500),
  CREATED_ON TIMESTAMP,
  CREATED_BY VARCHAR2(50),
  UPDATED_ON TIMESTAMP,
  UPDATED_BY VARCHAR2(50)
);

COMMIT;
