-- Seed BIZ_PROCESS and BIZ_PROCESS_STATES so Core can resolve all managers by ClassName/MethodName.
-- Each manager has at least one state row; linked to a generic config process (channel 1, messageType 2).

-- One additional process for "BasicConfiguration" style flows
INSERT INTO BIZ_PROCESS (BIZPROCESSID, BIZPROCESSNAME, CHANNELID, MESSAGETYPE, DESCRIPTION, ACTION_TYPE)
VALUES (2, 'BasicConfigurationProcess', 1, 2, 'Bank, Branch, City, Currency, etc.', 1);

-- State rows: CLASSNAME must match manager bean simple name (e.g. BankManager, GroupManager)
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (2, 'BankManager', 'SearchBank', 2, NULL, NULL, 1);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (3, 'BranchManager', 'SearchBranch', 2, NULL, NULL, 2);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (4, 'CityManager', 'SearchCity', 2, NULL, NULL, 3);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (5, 'CountryManager', 'SearchCountry', 2, NULL, NULL, 4);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (6, 'CurrencyManager', 'SearchCurrency', 2, NULL, NULL, 5);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (7, 'GroupManager', 'SearchGroup', 2, NULL, NULL, 6);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (8, 'PermissionManager', 'GetAllPermissions', 2, NULL, NULL, 7);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (9, 'PolicyManager', 'GetAllPolicies', 2, NULL, NULL, 8);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (10, 'UserManager', 'GetAllUsers', 2, NULL, NULL, 9);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (11, 'PasswordPolicyManager', 'GetAllPasswordPolicies', 2, NULL, NULL, 10);
INSERT INTO BIZ_PROCESS_STATES (PROCESSSTATEID, CLASSNAME, METHODNAME, BIZPROCESSID, NEXTSEQNUM_SUCCESS, NEXTSEQNUM_FAIL, SEQUENCENUMBER)
VALUES (12, 'SearchFilterManager', 'GetSearchFilters', 2, NULL, NULL, 11);

COMMIT;
