-- Card domain tables for CMS (Oracle 19c)
-- Creates CARD_STATUS, CARD_TYPE, CARD_PRODUCT, CARD_PRODUCTION_STATUS, CARD, CARD_REQUEST, CARD_ACCOUNT
-- Uses conditional creation: skip if table already exists (ORA-00955)

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CARD_STATUS (
    CARD_STATUS_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
    CARD_STATUS_NAME VARCHAR2(255),
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR2(50)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CARD_PRODUCT (
    PRODUCT_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(255),
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    IS_ACTIVE NUMBER(1)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CARD_PRODUCTION_STATUS (
    CARD_PROD_STATUS_ID VARCHAR2(50) NOT NULL PRIMARY KEY,
    CARD_PROD_STATUS_NAME VARCHAR2(255),
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR2(50)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CARD_TYPE (
    CARD_TYPE_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
    IS_SUPP_TYPE NUMBER(1),
    SUPP_TYPE_CODE VARCHAR2(50),
    CARD_TYPE_NAME VARCHAR2(255),
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    SUPPLEMENTARY_ALLOWED NUMBER(19),
    PRODUCT_CODE VARCHAR2(50),
    IS_ACTIVE NUMBER(1),
    PAN_LENGTH NUMBER(10),
    BIN NUMBER(10),
    EXP_PERIOD NUMBER(10),
    PAN_SEQUENCE_NAME VARCHAR2(100),
    PAN_SEQUENCE_LENGTH NUMBER(10),
    CONSTRAINT FK_CARD_TYPE_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES CARD_PRODUCT(PRODUCT_CODE)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CARD (
    CARD_ID NUMBER(19) NOT NULL PRIMARY KEY,
    PAN VARCHAR2(50),
    RELATIONSHIP_NUM VARCHAR2(50),
    CARD_TITLE VARCHAR2(255),
    EXPIRY_DATE TIMESTAMP,
    CARD_TYPE_CODE VARCHAR2(50),
    LIMIT_PROFILE VARCHAR2(50),
    SUPPLEMENTARY_COUNT NUMBER(10),
    CARD_STATUS_CODE VARCHAR2(50),
    PRIMARY_CARD_NUM VARCHAR2(50),
    ACTIVATION_DATE TIMESTAMP,
    PRODUCT_CODE VARCHAR2(50),
    ISSUED_DATE TIMESTAMP,
    BRANCH_CODE VARCHAR2(50),
    CARD_PROD_STATUS_ID VARCHAR2(50),
    WHEN_DELETED TIMESTAMP,
    IS_REPLACED NUMBER(1) DEFAULT 0,
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    REQUEST_TYPE VARCHAR2(50),
    TRIM_PAN VARCHAR2(50),
    IS_MAKER NUMBER(1),
    TO_CARD_STATUS_CODE VARCHAR2(50),
    ECOMMERCE_ALLOWED VARCHAR2(10),
    CVV VARCHAR2(20),
    CVV2 VARCHAR2(20),
    ICVV VARCHAR2(20),
    TRACK1_DATA VARCHAR2(500),
    TRACK2_DATA VARCHAR2(500),
    TO_CARD_TITLE VARCHAR2(255),
    TO_CARD_TYPE_CODE VARCHAR2(50),
    TO_DEBIT_PROD_CODE VARCHAR2(50),
    OPERATION_TYPE VARCHAR2(50),
    CONSTRAINT UK_CARD_PAN UNIQUE (PAN),
    CONSTRAINT FK_CARD_BRANCH FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH(BRANCH_CODE),
    CONSTRAINT FK_CARD_STATUS FOREIGN KEY (CARD_STATUS_CODE) REFERENCES CARD_STATUS(CARD_STATUS_CODE),
    CONSTRAINT FK_CARD_PROD_STATUS FOREIGN KEY (CARD_PROD_STATUS_ID) REFERENCES CARD_PRODUCTION_STATUS(CARD_PROD_STATUS_ID)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CARD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CARD_REQUEST (
    REQUEST_ID NUMBER(19) NOT NULL PRIMARY KEY,
    RELATIONSHIP_NUM VARCHAR2(50),
    ACCOUNT_NUM VARCHAR2(50),
    CARD_TITLE VARCHAR2(255),
    CARD_TYPE_CODE VARCHAR2(50),
    PRODUCT_CODE VARCHAR2(50),
    BRANCH_CODE VARCHAR2(50),
    SUPPLEMENTARY_COUNT NUMBER(10) DEFAULT 0,
    IS_PROCESSED NUMBER(1) DEFAULT 0,
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    PROGRESS_FLAG NUMBER(10) DEFAULT 0,
    REQUEST_TYPE_ID VARCHAR2(50),
    PRIMARY_PAN VARCHAR2(50),
    CONSTRAINT FK_CARD_REQ_TYPE FOREIGN KEY (CARD_TYPE_CODE) REFERENCES CARD_TYPE(CARD_TYPE_CODE),
    CONSTRAINT FK_CARD_REQ_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES CARD_PRODUCT(PRODUCT_CODE)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CARD_REQUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CARD_ACCOUNT (
    PAN VARCHAR2(50) NOT NULL,
    ACCOUNT_NUM VARCHAR2(50) NOT NULL,
    EFFECTIVE_FROM TIMESTAMP,
    RELATIONSHIP_NUM VARCHAR2(50),
    EFFECTIVE_TO TIMESTAMP,
    IS_OVERALL_DEFAULT NUMBER(1) DEFAULT 0,
    IS_ACCT_TYPE_DEFAULT NUMBER(1) DEFAULT 0,
    CREATED_ON TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    PRIMARY KEY (PAN, ACCOUNT_NUM),
    CONSTRAINT FK_CARD_ACCT_CARD FOREIGN KEY (PAN) REFERENCES CARD(PAN),
    CONSTRAINT FK_CARD_ACCT_ACCOUNT FOREIGN KEY (ACCOUNT_NUM) REFERENCES ACCOUNT(ACCOUNT_NUM)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMIT;
