-- Seed card lookup data for dropdowns and valid references
INSERT INTO CARD_STATUS (CARD_STATUS_CODE, CARD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'ACTIVE', 'Active', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_STATUS WHERE CARD_STATUS_CODE = 'ACTIVE');
INSERT INTO CARD_STATUS (CARD_STATUS_CODE, CARD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'INACTIVE', 'Inactive', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_STATUS WHERE CARD_STATUS_CODE = 'INACTIVE');
INSERT INTO CARD_STATUS (CARD_STATUS_CODE, CARD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'CLOSED', 'Closed', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_STATUS WHERE CARD_STATUS_CODE = 'CLOSED');

INSERT INTO CARD_PRODUCTION_STATUS (CARD_PROD_STATUS_ID, CARD_PROD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'PENDING', 'Pending', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_PRODUCTION_STATUS WHERE CARD_PROD_STATUS_ID = 'PENDING');
INSERT INTO CARD_PRODUCTION_STATUS (CARD_PROD_STATUS_ID, CARD_PROD_STATUS_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'ISSUED', 'Issued', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_PRODUCTION_STATUS WHERE CARD_PROD_STATUS_ID = 'ISSUED');

INSERT INTO CARD_PRODUCT (PRODUCT_CODE, PRODUCT_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, IS_ACTIVE)
SELECT 'DEBIT', 'Debit Card', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_PRODUCT WHERE PRODUCT_CODE = 'DEBIT');
INSERT INTO CARD_PRODUCT (PRODUCT_CODE, PRODUCT_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, IS_ACTIVE)
SELECT 'CREDIT', 'Credit Card', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_PRODUCT WHERE PRODUCT_CODE = 'CREDIT');

INSERT INTO CARD_TYPE (CARD_TYPE_CODE, CARD_TYPE_NAME, PRODUCT_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, SUPPLEMENTARY_ALLOWED, IS_ACTIVE, PAN_LENGTH, BIN, EXP_PERIOD, PAN_SEQUENCE_NAME, PAN_SEQUENCE_LENGTH)
SELECT 'DEBIT_STD', 'Debit Standard', 'DEBIT', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system', 0, 1, 16, 0, 60, 'CARD_PAN_SEQ', 10 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_TYPE WHERE CARD_TYPE_CODE = 'DEBIT_STD');
INSERT INTO CARD_TYPE (CARD_TYPE_CODE, CARD_TYPE_NAME, PRODUCT_CODE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY, SUPPLEMENTARY_ALLOWED, IS_ACTIVE, PAN_LENGTH, BIN, EXP_PERIOD, PAN_SEQUENCE_NAME, PAN_SEQUENCE_LENGTH)
SELECT 'CREDIT_STD', 'Credit Standard', 'CREDIT', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system', 0, 1, 16, 0, 60, 'CARD_PAN_SEQ', 10 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CARD_TYPE WHERE CARD_TYPE_CODE = 'CREDIT_STD');

COMMIT;
