-- Remove BIZ_PROCESS_STATES rows for managers whose entities are being dropped
DELETE FROM BIZ_PROCESS_STATES WHERE CLASSNAME IN ('BankManager','CityManager','CountryManager','CurrencyManager','SearchFilterManager');

-- Group A: tables with no API, no use in card or auth
DROP TABLE BIZ_PROCESS_ASSEMBLY;
DROP TABLE USM_APPLICATION;
DROP TABLE SYSTEM_CONFIGURATION;
DROP TABLE REPORT_CONNECTION_STRING;
DROP TABLE SCHEMA_METADATA;
DROP TABLE SCHEMA_METADATA_TABLE;
DROP TABLE SEARCH_FILTER_BINDING;
DROP TABLE AUDIT_LOG_FIELD;
DROP TABLE AUDIT_LOG_ENTITY;
DROP TABLE AUDIT_LOG_BATCH;
DROP TABLE META_COUNTER;
DROP TABLE COUNTER_VALUE;
DROP TABLE APPLICATION_SEQUENCE;
DROP TABLE BANK_ENTITY;
DROP TABLE BANK_SYSTEM;
DROP TABLE CACHE_ITEM_INFO;

-- Group B: reference data tables (drop dependents first where applicable)
DROP TABLE TRANSACTION_CODE;
DROP TABLE TRANSACTION_GROUP;
DROP TABLE SEARCH_FILTER;
DROP TABLE DEVICE_FACTORY;
DROP TABLE DEVICE_TYPE;
DROP TABLE DEVICE_USAGE;
DROP TABLE ACCOUNT_OFFICER;
DROP TABLE ACTION_TYPE;
DROP TABLE INSTRUMENT;
DROP TABLE TITLE;
DROP TABLE RELIGION;
DROP TABLE OCCUPATION;
DROP TABLE MARITAL_STATUS;
DROP TABLE NATIONALITY;
DROP TABLE LANGUAGE;
DROP TABLE GENDER;
DROP TABLE CUSTOMER_TYPE;
DROP TABLE CHANNEL;
DROP TABLE CURRENCY;
DROP TABLE CITY;
DROP TABLE COUNTRY;
DROP TABLE BANK;

COMMIT;
