-- Seed minimal master data to run the system (account status/type, branch)

INSERT INTO ACCOUNT_STATUS (ACCT_STATUS_CODE, ACCT_STATUS_NAME, DESCRIPTION, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'OPEN', 'Open', 'Account is open', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ACCOUNT_STATUS WHERE ACCT_STATUS_CODE = 'OPEN');
INSERT INTO ACCOUNT_STATUS (ACCT_STATUS_CODE, ACCT_STATUS_NAME, DESCRIPTION, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'CLOSED', 'Closed', 'Account is closed', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ACCOUNT_STATUS WHERE ACCT_STATUS_CODE = 'CLOSED');

INSERT INTO ACCOUNT_TYPE (ACCT_TYPE_CODE, ACCT_TYPE_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'SAVINGS', 'Savings', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ACCOUNT_TYPE WHERE ACCT_TYPE_CODE = 'SAVINGS');
INSERT INTO ACCOUNT_TYPE (ACCT_TYPE_CODE, ACCT_TYPE_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'CURRENT', 'Current', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ACCOUNT_TYPE WHERE ACCT_TYPE_CODE = 'CURRENT');

INSERT INTO BRANCH (BRANCH_CODE, BRANCH_NAME, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY)
SELECT 'MAIN', 'Main Branch', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM BRANCH WHERE BRANCH_CODE = 'MAIN');

COMMIT;
