-- Run manually when Flyway is disabled (spring.flyway.enabled=false).
-- Required so mobile card-request approve auto-assigns LIMIT_PROFILE = STD.

INSERT INTO LIMIT_PROFILE (
  ID, PROFILE_CODE, PROFILE_NAME, CURRENCY_CODE,
  ATM_DAILY_AMOUNT, ATM_MONTHLY_AMOUNT, ATM_YEARLY_AMOUNT,
  POS_DAILY_AMOUNT, POS_MONTHLY_AMOUNT, POS_YEARLY_AMOUNT,
  ECOMMERCE_DAILY_AMOUNT, ECOMMERCE_MONTHLY_AMOUNT, ECOMMERCE_YEARLY_AMOUNT,
  IS_ACTIVE, CREATED_ON, CREATED_BY, UPDATED_ON, UPDATED_BY
)
SELECT LIMIT_PROFILE_SEQ.NEXTVAL, 'STD', 'Standard Limit', 'PKR',
  50000, 500000, 2000000,
  100000, 1000000, 5000000,
  50000, 500000, 2000000,
  1, SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM LIMIT_PROFILE WHERE PROFILE_CODE = 'STD');

COMMIT;
